# Site settings
title: SPICE Engineering Camp
# email: your-email@domain.com
description: "SPICE Engineering Camp - Pinball Machines!"
url: "http://ayocom.github.io/spice-pinball"
timezone: America/Los_Angeles


# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

# From Jekyll Site
relative_permalinks: false

# For gh-pages
safe: true
lsi: false
source: .